// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vktlkhdkrnajwwsygrrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdGxraGRrcm5hand3c3lncnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTA3MjgsImV4cCI6MjA2ODY2NjcyOH0.T-HQmyu2W5a3wwIlubEpb9HuIcjV_o8NhDQP2gCkvuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});